[package]
name = "haste_map"
version = "0.1.0"
authors = ["Jordan Eldredge <jordan@jordaneldredge.com>"]

[dependencies]
glob = "0.2.11"
regex = "0.2"
serde = "1.0.58"
serde_derive = "1.0.58"
serde_json = "1.0.17"
lazy_static = "1.0"
bincode = "1.0.0"
rayon = "1.0"